### ISSUE TITLE
will there ever be a time when the comment part is not needed?

### ISSUE THREAD

**Issue by rchrdnsh** [mjbvz/vscode-comment-tagged-templates#1]
No biggie, but it would be even cooler if this worked without the comment part, just being able to write...

```
html
```

...instead of...

```
/* html */
```

...but if not, then no worries, it's still absolutely awesome, and thank you very much for this! XD

R

**Comment by mjbvz** [comment]
See this extension: https://github.com/mjbvz/vscode-lit-html

Code like:

```ts
html`<a>`
```

requires that a template function `html` is defined in the current scope. Otherwise the program is invalid. That's why using comments for marking the language is preferable in many cases
