### ISSUE TITLE
Does not work inside script tags in .html files

### ISSUE THREAD

**Issue by janispritzkau** [mjbvz/vscode-comment-tagged-templates#10]
Could this be implemented easily? I don't know anything about vscode extension development, but I think different scopes need to be added to get this to work inside html script tags.

**Comment by mjbvz** [comment]
PRs welcome. You need to modify the [injection grammar's](https://github.com/Microsoft/vscode-docs/blob/master/api/language-extensions/syntax-highlight-guide.md#injection-grammars) scope so that it also targets html script blocks

**Comment by janispritzkau** [comment]
I did quite a bit of research and haven't found anything that does explain how to do this.

This seems related: https://github.com/microsoft/vscode/issues/1751

**Comment by janispritzkau** [comment]
Just as I wrote it I found a solution. Adding `text.html.derivative` to the target scopes does work.

**Comment by mjbvz** [comment]
Fixed by #11
