### ISSUE TITLE
Support for other host languages

### ISSUE THREAD

**Issue by markusjohnsson** [mjbvz/vscode-comment-tagged-templates#13]
Is the extension very much tied to the JS/TS syntax, and/or would it be possible to support other "host" languages? For example, I have a bunch of C# code with javascript embedded:

```cs
        [JsImport(@"
            function (T) {
                return function FromJsArray(arr) {
                    var r = new (asm0['System.Array`1'](T))();
                    r.etype = T;
                    r.jsarr = arr;
                    return r;
                };
            }")]
        internal extern static T[] FromJsArray<T>(object array);
```

**Comment by mjbvz** [comment]
This extension is JS/TS specific but that general approach should work for other languages too. Take a look at how this extension uses [injection grammars](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars) and see if you can do the same for C# (you probably just need to find the right grammar scopes to target)
