### ISSUE TITLE
Causing syntax of following block to change

### ISSUE THREAD

**Issue by seaneking** [mjbvz/vscode-comment-tagged-templates#16]
Using this in a fresh project it changes the syntax of whatever block follows the tagged template as well.

Eg: 
```js
const styles = /* css */ `
  color: pink;
`;

// This function thinks it's CSS
function someFunction() {

}

// This function knows it's JavaScript
function anotherFunction() {

}
```

Makes this otherwise perfect plugin for my use-case impossible to use. Any ideas?

**Comment by seaneking** [comment]
Seems to be just overflowing the block it's assigned to. For example if I wrap the string literal in an object it's fine

```js
const styles = {
  button: /* css */ `
 	color: pink;
  `
};

// This works fine now
function someFunction() {

}
```

**Comment by panoply** [comment]
It's invalid css, as your defining properties, outside of a class name.

**Comment by mjbvz** [comment]
Closing this as out of scope since this invalid css. If someone wants to try preventing this from happening, I'd take a PR
