### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by 19majkel94** [mjbvz/vscode-comment-tagged-templates#2]
It would be nice if this extensions support also GraphQL tagged templates :wink:	

![image](https://user-images.githubusercontent.com/10618781/42375748-d91ea71a-811c-11e8-9d4b-fc1c3c942792.png)

**Comment by mjbvz** [comment]
Contributions welcome: https://github.com/mjbvz/vscode-comment-tagged-templates#contributing

**Comment by axefrog** [comment]
I want markdown support myself, so I've added it and graphql in a PR: https://github.com/mjbvz/vscode-comment-tagged-templates/pull/4

**Comment by mjbvz** [comment]
Fixed by #4

**Comment by roch-numbered** [comment]
I know this is an old topic that has been closed but regarding this comment on https://github.com/mjbvz/vscode-comment-tagged-templates/pull/4#discussion_r534640580, is it intentional? I found it confusing to use `qgl` instead of `gql` 😕
