### ISSUE TITLE
No highlighting with semantic highlighting enabled

### ISSUE THREAD

**Issue by texastoland** [mjbvz/vscode-comment-tagged-templates#24]
The correct scopes are injected but not highlighted anymore regardless of theme. Is this a known limitation? Maybe Code or LSP bug?

**Comment by mjbvz** [comment]
Doesn't appear to be the case for me. If you're still seeing this, please provide steps to reproduce the problem

**Comment by microhobby** [comment]
@mjbvz by simply adding the:

```json
"editor.semanticTokenColorCustomizations": {
        "enabled": true,
    },
```

this makes the comments not work anymore:

![image](https://github.com/mjbvz/vscode-comment-tagged-templates/assets/2633321/5237a7db-dbbc-4469-b88c-8ef01876d353)

**Comment by microhobby** [comment]
@texastoland are you able to workaround this?

**Comment by texastoland** [comment]
Sorry I missed the original notification and haven't used it recently 🙏🏼

> ```json
> "editor.semanticTokenColorCustomizations": {
>         "enabled": true,
>     },
> ```

Thanks that was likely when it started for me too!
