### ISSUE TITLE
Add support for rust raw string literals

### ISSUE THREAD

**Issue by Purpzie** [mjbvz/vscode-comment-tagged-templates#26]
Rust doesn't have backtick `` ` `` strings, but it does have [raw string literals](https://doc.rust-lang.org/reference/tokens.html#raw-string-literals) which can span multiple lines. This extension understandably doesn't handle those, but it would be neat if it could.

**Comment by mjbvz** [comment]
Sounds like a better fit for another extension since this one is focused on JS/TS support
