### ISSUE TITLE
Support for prettier inside template literals

### ISSUE THREAD

**Issue by Rafi993** [mjbvz/vscode-comment-tagged-templates#28]
* Right now prettier does not work inside template literal when using this extension
* Since most developers will use prettier or other extensions to fix for formatting. Formatting should also work inside template literals

**Comment by mjbvz** [comment]
This is something that prettier would have to implement. It's out of scope for this extension

**Comment by Sec-ant** [comment]
Hey, I've developed a prettier plugin [`prettier-plugin-embed`](https://github.com/Sec-ant/prettier-plugin-embed) and it can format embedded languages identified by customized comment tags. It works well with this extension. I'm expecting feedbacks.
