### ISSUE TITLE
configurable grammar

### ISSUE THREAD

**Issue by leemhenson** [mjbvz/vscode-comment-tagged-templates#3]
Hi, would it be possible to make the grammar configurable? We've already got a function that we use to wrap our sql queries, e.g.:

```ts
SQL`SELECT * FROM tableA`
```

and while I can add 

```ts
SQL/* sql */`SELECT * FROM tableA`
```

it's not quite as neat as it could be if this extension could be told to recognise `SQL` as an identifier of sql strings.

**Comment by mjbvz** [comment]
Probably a better fit for a separate extension, see https://github.com/mjbvz/vscode-lit-html for example
