### ISSUE TITLE
GLSL template breaks syntax highlighting in TS file

### ISSUE THREAD

**Issue by thatcort** [mjbvz/vscode-comment-tagged-templates#6]
When I add a GLSL comment tag inside a Typescript file the shader becomes correctly highlighted, but the rest of the file loses all syntax highlighting

**Comment by mjbvz** [comment]
Please provide example code

**Comment by thatcort** [comment]
Here's a screenshot showing what it looks like.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/12662578/46171708-518aa800-c26f-11e8-9aa3-30ccbcadb261.png">

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by gkjohnson** [comment]
I'm seeing this in all javascript files. I tried disabling all of extensions my to get it to work, as well. 

![image](https://user-images.githubusercontent.com/734200/50803769-eb66e580-129f-11e9-9121-e21e64052618.png)

#### Repro
1. Create a new file in VSCode
2. Save it with a `.js` file extension
3. Paste the following code in:
```js
const test = /* glsl */`
varying vec2 vUv;
uniform mat3 uvTransform;

void main() {

}
`;
```
4. Broken syntax highlighting.

Thanks for putting this project together, by the way! I'm hoping it'll make deving shader code a lot nicer for us!

**Comment by mjbvz** [comment]
I suspect the issue was that you did not have an extension that provides glsl syntax highlighting installed. For these cases, I've fixed this extension so that it will now highlight the comment body as a constant color

**Comment by gkjohnson** [comment]
Oh that fixed it -- fantastic. Somehow I missed that in the docs. Thank you!
