### ISSUE TITLE
Consideration: Common patterns involving actual tagged-template syntax

### ISSUE THREAD

**Issue by SMotaal** [mjbvz/vscode-comment-tagged-templates#8]
It is really awesome to see in action the full highlighting capabilities this plugin allows, without all the baggage of tracking scoped identifiers or worrying about being too opinionated over what users do with actual code.

While those slower issues pan out (assuming people are trying different concepts) did you consider how people might be using it along with the actual tags (ie ``md /* md */ `…`;``) and maybe there are opportunities to make this feel a little less painfully verbose?

Some directions here: 

**Explicit** (ie pre-prefix)

- Explicit prefix of identifier: ``/* md */ md`…`;``
  > avoids discontinuity problems and/or confusion

- Explicit prefix of expression:  ``/* md */ (x.md || y.md)`…`;``
  > same deal and likely as intuitive 

**Implicit** (using `/**/` or `/*/*/`)

- Implicit prefix of identifier: ``/**/ md`…`;``
  > reasonable to infer from closest identifier before opening tick

- Implicit prefix of intuitive expression:  ``/**/ (x.md || y.md)`…`;``
  > same deal and likely as intuitive

- Implicit prefix of confusing expression:  ``/**/ (y.css || y.md)`…`;``
  > less intuitive but user will know and can opt to coerce the correct syntax — imho this would be `md` not `css` btw

---

**Relates to**: #1 #3

**Comment by mjbvz** [comment]
Interesting proposals but out of scope for this plugin. If you have a well known tag name—such as `css` or `md`—a more specialized library like [styled components](https://github.com/styled-components/vscode-styled-components) is probably a better fit
